### ISSUE TITLE
Firebase cloud functions deployment error

### ISSUE THREAD

**Issue by GCoe** [ampproject/amp-toolbox#215]
My app is ok with locar serve but I got an error on cors.js when trying to deploy to Firebase cloud : 
Any thoughts please ?

The error log : 

`Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/node_modules/amp-toolbox-cors/lib/cors.js:46
  return async (request, response, next) => {
               ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/amp-toolbox-cors/index.js:18:18)`

**Comment by sebastianbenz** [comment]
Closing as unrelated to amp toolbox.
