### ISSUE TITLE
Node example on README doesn't work

### ISSUE THREAD

**Issue by ibrahimcesar** [ampproject/amp-toolbox#869]
Tried the example provide to test locally with Node and the code provided returns error:

```
linter.MetaCharsetIsFirst(context).then(console.log);
       ^

TypeError: linter.MetaCharsetIsFirst is not a function
    at Object.<anonymous> (/Users/ibrahim.souza/Projetos/webstories-linter/linter.js:12:8)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Only through local build I got the result expected to evaluate our code. Since we are a small team, if this worked as documented would be better for our team non-technical run the commands without the hassle of build this repo and navigate through folders

Node version: **12.18.0
Npm version: 6.14.4
System: Mac OSX 10.15.5
@ampproject/toolbox-linter: **2.5.12**

**Comment by ithinkihaveacat** [comment]
Can you provide the commands you ran to install and compile the dependencies?

Also, are you aware of the pre-built [command-line tool](https://www.npmjs.com/package/@ampproject/toolbox-cli#lint)?

```sh
# install "amp" tool globally
$ npm install @ampproject/toolbox-cli -g
# lint https://amp.dev
$ amp lint https://amp.dev
```
