### ISSUE TITLE
TypeError: DomHandler is not a constructor

### ISSUE THREAD

**Issue by anooplath** [ampproject/amp-toolbox#927]
Hello,

I am getting below error:

`TypeError: DomHandler is not a constructor
    at eval (webpack-internal:///../node_modules/@ampproject/toolbox-optimizer/lib/TreeParser.js:43:23)
    at new Promise (<anonymous>)
    at TreeParser.parse (webpack-internal:///../node_modules/@ampproject/toolbox-optimizer/lib/TreeParser.js:42:12)
    at DomTransformer.transformHtml (webpack-internal:///../node_modules/@ampproject/toolbox-optimizer/lib/DomTransformer.js:126:35)
    at Object._callee$ (webpack-internal:///./server.js:616:43)
    at tryCatch (D:\dev\nbt\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (D:\dev\nbt\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (D:\dev\nbt\node_modules\regenerator-runtime\runtime.js:117:21)
`

"@ampproject/toolbox-optimizer": "^2.6.0",

**Comment by sebastianbenz** [comment]
This should've been fixed in the meantime.
